### ISSUE TITLE
Access to googlesheet 

### ISSUE THREAD

**Issue by leoneler1980** [USAID-OHA-SI/selfdestructin5#35]
Hi, I was trying to use selfdesctructin5::make_mdb_df()  but within  USAID network the access to the connection with Tidyverse API is blocked, Is possible to work with this package without connecting to the internet?

**Comment by tessam30** [comment]
this has been fixed in the dev version and should now work without the need to access the USAID network. Note, if you are using the resolved known issues option, you will need to be connected to the network.
